"use strict";
exports.__esModule = true;
exports.PayStack = exports.verifyOTP = exports.generateOTP = exports.Http = exports.verifyToken = exports.generateToken = exports.compareHash = exports.hash = exports.deleteData = exports.updateManyData = exports.updateData = exports.readsingleData = exports.readData = exports.createData = exports.connect = void 0;
var database_1 = require("./database");
exports.connect = database_1.connect;
exports.createData = database_1.createData;
exports.readData = database_1.readData;
exports.readsingleData = database_1.readsingleData;
exports.updateData = database_1.updateData;
exports.updateManyData = database_1.updateManyData;
exports.deleteData = database_1.deleteData;
var encrypt_1 = require("./encrypt");
exports.hash = encrypt_1.hash;
exports.compareHash = encrypt_1.compareHash;
var token_1 = require("./token");
exports.generateToken = token_1.generateToken;
exports.verifyToken = token_1.verifyToken;
var Http_1 = require("./Http");
exports.Http = Http_1["default"];
var otp_1 = require("./otp");
exports.generateOTP = otp_1.generateOTP;
exports.verifyOTP = otp_1.verifyOTP;
var PayStack_1 = require("./PayStack");
exports.PayStack = PayStack_1["default"];
